kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 5tcIdxCIKn1/BDExcPSd25tI6RUDkOtV9zFqRTAx2xE=
      - identity: {}